name: CI
on:
  push:
    paths-ignore:
    - '.vscode'
    - '*.md'
    - 'LICENCE'

jobs:
  linux:
    name: Linux build on node ${{ matrix.node_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [8.x, 10.x]
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set Node.js version ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}

    - name: Install packages
      run: npm install

    - name: Run build
      run: npm run build:linux

    - name: Moving build to artifacts directory
      run: bash ./scripts/move-files.sh linux

    - name: Upload linux build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: "linux-${{ matrix.node_version }}"
        path: "dist/artifacts"

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"

    - name: Notification
      uses: gitthermal/discord-notification-action@master
      with:
        webhook_url: ${{ secrets.DISCORD_CI_WEBHOOK }}
        os: Linux
        node_version: ${{ matrix.node_version }}
        workflow_name: CI


